[package]
name = "simple_nn"
version = "0.1.0"
authors = ["Toke Horn Brorholt <etok414@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.10.0"
